// Defaults to the site owner's AdSense publisher ID so ads work without env vars.
// Override via VITE_ADSENSE_CLIENT if needed.
export const ADSENSE_CLIENT = (import.meta.env.VITE_ADSENSE_CLIENT || "ca-pub-5325347113196186").trim();

export const ADSENSE_SLOTS = {
  TOP_BANNER: import.meta.env.VITE_ADSENSE_SLOT_TOP_BANNER || "",
  HOME_MID_RECTANGLE: import.meta.env.VITE_ADSENSE_SLOT_HOME_MID_RECTANGLE || "",
  HOME_BOTTOM_RECTANGLE: import.meta.env.VITE_ADSENSE_SLOT_HOME_BOTTOM_RECTANGLE || "",
  TAB_TOP_BANNER: import.meta.env.VITE_ADSENSE_SLOT_TAB_TOP_BANNER || "",
  TAB_BOTTOM_RECTANGLE: import.meta.env.VITE_ADSENSE_SLOT_TAB_BOTTOM_RECTANGLE || "",
  PREDICTIONS_IN_ARTICLE: import.meta.env.VITE_ADSENSE_SLOT_PREDICTIONS_IN_ARTICLE || "",
};

export const BETTING_SPONSORS = [
  {
    id: "stake",
    name: "Stake",
    url: import.meta.env.VITE_STAKE_AFFILIATE_URL || "https://stake.com",
    label: "Featured sportsbook",
    offer: "Crypto bonus on World Cup markets",
    accentClass: "from-emerald-400 to-lime-300",
  },
  {
    id: "rainbet",
    name: "Rainbet",
    url: import.meta.env.VITE_RAINBET_AFFILIATE_URL || "https://rainbet.com",
    label: "Crypto casino & sportsbook",
    offer: "Welcome bonus + rakeback",
    accentClass: "from-indigo-400 to-violet-300",
  },
  {
    id: "1xbet",
    name: "1xBet",
    url: import.meta.env.VITE_1XBET_AFFILIATE_URL || "https://1xbet.com",
    label: "Match odds partner",
    offer: "Up to €130 welcome bonus",
    accentClass: "from-sky-400 to-cyan-300",
  },
  {
    id: "betano",
    name: "Betano",
    url: import.meta.env.VITE_BETANO_AFFILIATE_URL || "https://www.betano.com",
    label: "Odds boosts & live betting",
    offer: "Bet boosts on every match",
    accentClass: "from-orange-400 to-amber-300",
  },
];

export const RESPONSIBLE_GAMBLING_URL = "https://www.begambleaware.org";

export const TABS = [
  { id: "home", label: "Home", path: "" },
  { id: "scores", label: "Fixtures", path: "fixtures" },
  { id: "predictions", label: "Predictions", path: "predictions" },
  { id: "groups", label: "Groups", path: "groups" },
  { id: "news", label: "News", path: "news" },
  { id: "games", label: "Games", path: "games" },
  { id: "scorers", label: "Top Scorers", path: "scorers" },
  { id: "about", label: "About", path: "about" },
];

export const COUNTRY_FLAGS = {
  Argentina: "ar",
  Algeria: "dz",
  Australia: "au",
  Austria: "at",
  Belgium: "be",
  "Bosnia & Herzegovina": "ba",
  Brazil: "br",
  Canada: "ca",
  "Cape Verde": "cv",
  Colombia: "co",
  Croatia: "hr",
  "Czech Republic": "cz",
  Czechia: "cz",
  "Cabo Verde": "cv",
  "C\u00f4te d'Ivoire": "ci",
  "Cote d'Ivoire": "ci",
  "Cura\u00e7ao": "cw",
  Curacao: "cw",
  "DR Congo": "cd",
  Ecuador: "ec",
  Egypt: "eg",
  England: "gb-eng",
  France: "fr",
  Germany: "de",
  Ghana: "gh",
  Haiti: "ht",
  Iran: "ir",
  "IR Iran": "ir",
  Iraq: "iq",
  "Ivory Coast": "ci",
  Japan: "jp",
  Jordan: "jo",
  Mexico: "mx",
  Morocco: "ma",
  Netherlands: "nl",
  "New Zealand": "nz",
  Norway: "no",
  Panama: "pa",
  Paraguay: "py",
  Portugal: "pt",
  Qatar: "qa",
  "Saudi Arabia": "sa",
  Scotland: "gb-sct",
  Senegal: "sn",
  "South Africa": "za",
  "South Korea": "kr",
  "Korea Republic": "kr",
  Spain: "es",
  Sweden: "se",
  Switzerland: "ch",
  Tunisia: "tn",
  Turkey: "tr",
  "T\u00fcrkiye": "tr",
  USA: "us",
  "United States": "us",
  Uruguay: "uy",
  Uzbekistan: "uz",
};

export const HOST_NATIONS = [
  {
    country: "United States",
    code: "us",
    venues: "11 venues",
    cities: "Atlanta, Boston, Dallas, Houston, Kansas City, Los Angeles, Miami, New York/New Jersey, Philadelphia, San Francisco Bay Area, Seattle",
  },
  {
    country: "Canada",
    code: "ca",
    venues: "2 venues",
    cities: "Toronto, Vancouver",
  },
  {
    country: "Mexico",
    code: "mx",
    venues: "3 venues",
    cities: "Guadalajara, Mexico City, Monterrey",
  },
];

export const VENUE_BY_GROUND = {
  Atlanta: "Atlanta Stadium",
  "Boston (Foxborough)": "Boston Stadium",
  "Dallas (Arlington)": "Dallas Stadium",
  Houston: "Houston Stadium",
  "Kansas City": "Kansas City Stadium",
  "Los Angeles (Inglewood)": "Los Angeles Stadium",
  "Miami (Miami Gardens)": "Miami Stadium",
  "New York/New Jersey (East Rutherford)": "New York New Jersey Stadium",
  Philadelphia: "Philadelphia Stadium",
  "San Francisco Bay Area (Santa Clara)": "Bay Area Stadium",
  Seattle: "Seattle Stadium",
  Toronto: "Toronto Stadium",
  Vancouver: "Vancouver Stadium",
  "Guadalajara (Zapopan)": "Guadalajara Stadium",
  "Mexico City": "Mexico City Stadium",
  "Monterrey (Guadalupe)": "Monterrey Stadium",
};

export const TEAM_RATINGS = {
  Argentina: 93,
  France: 93,
  Spain: 92,
  Brazil: 91,
  England: 90,
  Portugal: 89,
  Germany: 88,
  Netherlands: 87,
  Belgium: 85,
  Croatia: 84,
  Uruguay: 84,
  Colombia: 83,
  Morocco: 82,
  Switzerland: 81,
  USA: 80,
  Mexico: 80,
  Japan: 79,
  Senegal: 79,
  Austria: 78,
  Turkey: 78,
  "T\u00fcrkiye": 78,
  Ecuador: 77,
  Norway: 77,
  Sweden: 77,
  "South Korea": 76,
  "Korea Republic": 76,
  Australia: 74,
  Canada: 74,
  "Ivory Coast": 74,
  "C\u00f4te d'Ivoire": 74,
  Paraguay: 74,
  Scotland: 74,
  "Czech Republic": 73,
  Czechia: 73,
  Iran: 73,
  "IR Iran": 73,
  Tunisia: 73,
  Algeria: 72,
  Egypt: 72,
  Ghana: 72,
  Panama: 70,
  Qatar: 70,
  "Saudi Arabia": 70,
  Uzbekistan: 70,
  "South Africa": 69,
  "Bosnia & Herzegovina": 68,
  Iraq: 68,
  Jordan: 67,
  "New Zealand": 67,
  "DR Congo": 66,
  Haiti: 66,
  "Cape Verde": 65,
  "Cabo Verde": 65,
  "Cura\u00e7ao": 64,
};

export const SCORERS = [
  { name: "Kylian Mbappe", team: "France", countryCode: "fr", goals: 0, assists: 0, img: "KM" },
  { name: "Vinicius Jr.", team: "Brazil", countryCode: "br", goals: 0, assists: 0, img: "VJ" },
  { name: "Lionel Messi", team: "Argentina", countryCode: "ar", goals: 0, assists: 0, img: "LM" },
  { name: "Harry Kane", team: "England", countryCode: "gb-eng", goals: 0, assists: 0, img: "HK" },
  { name: "Lamine Yamal", team: "Spain", countryCode: "es", goals: 0, assists: 0, img: "LY" },
  { name: "Jude Bellingham", team: "England", countryCode: "gb-eng", goals: 0, assists: 0, img: "JB" },
  { name: "Rodrygo", team: "Brazil", countryCode: "br", goals: 0, assists: 0, img: "RO" },
  { name: "Cristiano Ronaldo", team: "Portugal", countryCode: "pt", goals: 0, assists: 0, img: "CR" },
];

export const NEWS_FALLBACK = [
  {
    title: "World Cup 2026 opening match: Mexico vs South Africa preview",
    tag: "PREVIEW",
    time: "Recently",
    link: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026",
    source: "FIFA",
  },
  {
    title: "Complete World Cup 2026 fixtures, groups, venues, and kickoff times",
    tag: "SCHEDULE",
    time: "Recently",
    link: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026",
    source: "FIFA",
  },
  {
    title: "World Cup 2026 predictions: group favorites and early knockout paths",
    tag: "ANALYSIS",
    time: "Recently",
    link: "#",
    source: "WC2026.live",
  },
  {
    title: "Host city guide: what fans should know before the expanded tournament",
    tag: "GUIDE",
    time: "Recently",
    link: "#",
    source: "WC2026.live",
  },
  {
    title: "Players to watch as the 48-team World Cup begins in North America",
    tag: "FEATURE",
    time: "Recently",
    link: "#",
    source: "WC2026.live",
  },
  {
    title: "How the new World Cup 2026 format changes qualification from groups",
    tag: "GUIDE",
    time: "Recently",
    link: "#",
    source: "WC2026.live",
  },
];
